//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SynthCity.rc
//
#define IDR_MENU_FILE                   101
#define IDR_ACCELERATOR_FILEMENU        102
#define IDR_MENU_FILEINSTRUMENT         103
#define IDD_MIDIPROPERTIES              104
#define IDD_INSTRUMENT_ADDTRACK         105
#define IDD_TRACKPROPERTIES_SYNTH       106
#define IDD_CREATEINSTRUMENT            107
#define IDD_TRACKPROPERTIES_WAV         108
#define IDC_EDIT_MIDIPROPERTIES_TEMPO   1001
#define IDC_TREE_MIDIPROPERTIES_TRACKS  1002
#define IDC_EDIT_MIDIPROPERTIES_TRACKDETAILS 1003
#define IDC_CHECK_MIDIPROPERTIES_STARTATFIRSTNOTE 1004
#define IDC_COMBO_ADDTRACK_PRESETS      1005
#define IDC_EDIT_ADDTRACK_NAME          1006
#define IDC_EDIT_CREATEINSTRUMENT_NAME  1007
#define IDC_EDIT_WAVPROPERTIES_FILENAME 1008
#define IDC_BUTTON_WAVPROPERTIES_FILEDIALOG 1009
#define IDC_PROPERTIES_AREA             1010
#define IDC_EDIT1                       1011
#define IDC_EDIT_SYNTHPROPERTIES_DURATION_BAR 1011
#define IDC_EDIT_SYNTHPROPERTIES_FREQUENCY 1012
#define IDC_EDIT2                       1013
#define IDC_EDIT_SYNTHPROPERTIES_DURATION_BEAT 1013
#define ID_FILE_LOADINSTRUMENT          40001
#define ID_FILE_EXIT                    40002
#define ID_FILE_LOADSONG                40003
#define ID_FILE_SAVESONG                40004
#define ID_ACCELERATOR_LOAD_INSTRUMENT  40005
#define ID_ACCELERATOR_LOAD_SONG        40006
#define ID_ACCELERATOR_SAVE_SONG        40007
#define ID_INSTRUMENT_ADDTRACK          40008
#define ID_FILE_NEWINSTRUMENT           40009
#define ID_FILE_NEWSONG                 40010
#define ID_FILE_SAVEINSTRUMENT          40011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40012
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
