//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SynthCity.rc
//
#define IDR_MENU_FILE                   101
#define IDR_ACCELERATOR_FILEMENU        102
#define IDR_MENU_FILEINSTRUMENT         103
#define IDD_MIDIPROPERTIES              104
#define IDD_INSTRUMENT_ADDSYNTHVOICE    105
#define IDC_EDIT_MIDIPROPERTIES_TEMPO   1001
#define IDC_TREE_MIDIPROPERTIES_TRACKS  1002
#define IDC_EDIT_MIDIPROPERTIES_TRACKDETAILS 1003
#define IDC_CHECK_ENSURE_NOTE0_AT_ZERO  1004
#define IDC_CHECK_STARTATFIRSTNOTE      1005
#define IDC_COMBO_ADDSYNTHVOICEPRESET   1009
#define IDC_EDIT_ADDSYNTHVOICE_PROPERTIES_FREQUENCY 1010
#define ID_FILE_LOADINSTRUMENT          40001
#define ID_FILE_EXIT                    40002
#define ID_FILE_LOADSONG                40003
#define ID_FILE_SAVESONG                40004
#define ID_ACCELERATOR_LOAD_INSTRUMENT  40005
#define ID_ACCELERATOR_LOAD_SONG        40006
#define ID_ACCELERATOR_SAVE_SONG        40007
#define ID_INSTRUMENT_ADDVOICE          40008
#define ID_FILE_NEWINSTRUMENT           40009
#define ID_FILE_NEWSONG                 40011
#define ID_FILE_SAVEINSTRUMENT          40012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40013
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
